version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: angel-test
    container_name: angel-test
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=angeltest
      - MONGO_PASSWORD=angeltest
      - MONGO_DB=test
      - MONGO_Collection=resultados
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app