{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "angel-test.serviceAccountName" . }}
  labels:
{{ include "angel-test.labels" . | nindent 4 }}
{{- end -}}
